import torch
print("PyTorch Version:", torch.__version__)
print("CUDA Available:", torch.cuda.is_available())
print("Device:", "GPU" if torch.cuda.is_available() else "CPU")
if torch.cuda.is_available():
    print("CUDA Version:", torch.version.cuda)
    print("Number of GPUs:", torch.cuda.device_count())
    print("Current CUDA Device:", torch.cuda.current_device())
    print("Current CUDA Device Name:", torch.cuda.get_device_name(torch.cuda.current_device()))
    print("Current GPU:", torch.cuda.get_device_name(0))
    print("CUDA Memory Allocated:", torch.cuda.memory_allocated(0))
    print("CUDA Memory Cached:", torch.cuda.memory_reserved(0))
    print("CUDA Memory Allocated (Total):", torch.cuda.memory_allocated())
    print("CUDA Memory Cached (Total):", torch.cuda.memory_reserved())
    print("CUDA Memory Allocated (Max):", torch.cuda.max_memory_allocated())
    print("CUDA Memory Cached (Max):", torch.cuda.max_memory_reserved())
